FROM lupusmichaelis/alpine-php7-composer:1.0.5

RUN apk update \
        && apk upgrade --no-cache \
        && apk add --no-cache \
			php7-pecl-apcu \
			php7-memcache \
			php7-xdebug \
		&& echo Apk done

RUN set -e; \
	{ \
		sed -i '/^;zend/s/;//' \
			/etc/php7/conf.d/xdebug.ini; \
		echo 'apc.enable_cli = 1' >> \
			/etc/php7/conf.d/apcu.ini; \
	}

CMD [ "composer", "build-release" ]

COPY ./bin ${ANVIL}/bin
COPY \
	./composer.json \
	${ANVIL}/
COPY ./src ${ANVIL}/src
