FROM lupusmichaelis/alpine-php7-composer:1.0.5

RUN apk add \
	php7-memcache \
	php7-xdebug \
	&& echo Apk done

RUN sed -i \
		-e '/^;zend/s/;//' \
			/etc/php7/conf.d/xdebug.ini;

COPY \
	./composer.json \
	${ANVIL}/

COPY ./src ${ANVIL}/src
COPY ./bin ${ANVIL}/bin

CMD [ "composer", "build-release" ]
