FROM lupusmichaelis/alpine-php7-composer:1.0.5

USER 0
RUN apk add \
	php7-pecl-apcu \
	php7-memcache \
	php7-xdebug \
	doxygen \
	&& echo Apk done

RUN set -e; \
	{ \
		sed -i '/^;zend/s/;//' \
			/etc/php7/conf.d/xdebug.ini; \
		echo 'apc.enable_cli = 1' >> \
			/etc/php7/conf.d/apcu.ini; \
	}
